#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, char *argv[]) {
    if (argc != 4) {
        fprintf(stderr, "Usage: %s <input_file> <output_header> <variable_name>\n", argv[0]);
        return 1;
    }

    const char *input_path = argv[1];
    const char *output_path = argv[2];
    const char *var_name = argv[3];

    FILE *in = fopen(input_path, "rb");
    if (!in) {
        fprintf(stderr, "Failed to open input: %s\n", input_path);
        return 1;
    }

    fseek(in, 0, SEEK_END);
    long input_size = ftell(in);
    fseek(in, 0, SEEK_SET);

    unsigned char *input_data = malloc(input_size);
    if (!input_data) {
        fprintf(stderr, "Memory allocation failed\n");
        fclose(in);
        return 1;
    }
    fread(input_data, 1, input_size, in);
    fclose(in);

    FILE *out = fopen(output_path, "w");
    if (!out) {
        fprintf(stderr, "Failed to open output: %s\n", output_path);
        free(input_data);
        return 1;
    }

    fprintf(out, "/* Auto-generated by embed_compress */\n");
    fprintf(out, "#ifndef URUNTIME_%s_EMBEDDED_H\n", var_name);
    fprintf(out, "#define URUNTIME_%s_EMBEDDED_H\n\n", var_name);
    fprintf(out, "#include <stddef.h>\n\n");
    fprintf(out, "const unsigned char %s[%zu] = {\n", var_name, (size_t)input_size);

    for (size_t i = 0; i < (size_t)input_size; i++) {
        if (i % 12 == 0) fprintf(out, "    ");
        fprintf(out, "0x%02x,", input_data[i]);
        if ((i + 1) % 12 == 0 || i == (size_t)input_size - 1) fprintf(out, "\n");
        else fprintf(out, " ");
    }

    fprintf(out, "};\n");
    fprintf(out, "const size_t %s_size = %zu;\n", var_name, (size_t)input_size);
    fprintf(out, "#endif\n");

    fclose(out);
    free(input_data);

    printf("Embedded %s: %ld bytes\n", input_path, input_size);
    return 0;
}
